nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs

# packageExtensions:
#   "docz-core@*":
#     dependencies:
#       "cross-spawn": "*"
#       "tslib": "*"
#       "opn": "*"
#   "docz@*":
#     dependencies:
#       "tslib": "*"
#   "gatsby-theme-docz@*":
#     dependencies:
#       "docz-core": "*"
#   "gatsby@*":
#     dependencies:
#       "babel-plugin-export-metadata": "*"
#       "@babel/plugin-proposal-decorators": "*"
#       "@babel/plugin-proposal-class-properties": "*"
#       "@babel/plugin-transform-classes": "*"
#   "gatsby-plugin-mdx@*":
#     dependencies:
#       "@emotion/core": "^10.0.0"
